[project]
name = "imageset-viewer"
version = "0.1.0"
description = ""
authors = [
    {name = "Ilya Fiks",email = "fiksii@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "image (>=1.5.33,<2.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "lxml (>=5.3.1,<6.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "natsort (>=8.4.0,<9.0.0)",
    "future (>=1.0.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
